### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by impshum** [nishant-boro/django_rest-vuejs-auth#12]
Needs updated to work I imagine. I had all manners of problems with `six` and other packages being old.

I'd love to see this example working.

**Comment by DevGrinch** [comment]
Me too !!

**Comment by dgleba** [comment]
I updated some of the packages in `requirements.txt`. I got past the `six` problems.

Then I got  ` Model class DjangoRestAuth.models.Mods doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

Then I see that there is no app folder -- just the projects folder.  That folder contains both settings.py and models.py.

It is really confusing when people don't follow the Django practices defined in the Django official tutorial. 

Why is there no app folder?  I am sure it works, but it makes it really hard to adjust to so many different hacks of the django system. Frustrating.

**Comment by ghost** [comment]
Kindly check the latest commits.The project has been updated to work with python3(3.6.9)
