### ISSUE TITLE
Use template repository at official SimpleJWT

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [nishant-boro/django_rest-vuejs-auth#14]
Hey nishant-boro! We've created a template repository at https://github.com/SimpleJWT/drf-SimpleJWT-vue

Please try it out so that it can become a bit of a standard rather than having so many tutorials online. We're also looking into implementing our long awaited PR for httpOnly cookies soon, so please let us know if you find any vulnerabilities or other difficulties.

**Comment by ghost** [comment]
Looks great!
