### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by SeraVault** [nishant-boro/django_rest-vuejs-auth#4]
This doesn't appear to implement registration/new user creation.  Is this correct?

**Comment by Nerphist** [comment]
There are no views for /api/token/logout/ and /register/, I guess people need to implement it themselves

**Comment by nishant-boro** [comment]
@Nerphist There are views for logout and register, look [here](https://github.com/nishant-boro/django_rest-vuejs-auth/blob/master/frontEnd/src/views/Register.vue) and here[here](https://github.com/nishant-boro/django_rest-vuejs-auth/blob/master/frontEnd/src/views/Logout.vuel)

**Comment by nishant-boro** [comment]
@SeraVault You're wrong. I have implemented registration.

**Comment by FernandoPieressa** [comment]
You have the implementation of the call from frontend but not on backend

**Comment by nishant-boro** [comment]
> You have the implementation of the call from frontend but not on backend

Yeah, you need to do that on your own.

**Comment by nishant-boro** [comment]
BTW, if anyone is reading this, I'm open to contributions on the registration part. If anyone has implemented this, you can send a pull request to this and I will merge it with mine.
