### ISSUE TITLE
No URL token/logout

### ISSUE THREAD

**Issue by mikenowakme** [nishant-boro/django_rest-vuejs-auth#7]
I think there is no logout mechanism in djangorestframework-simplejwt, correct?

**Comment by nishant-boro** [comment]
Yes. Here, Logout is initialized by informing the backend to blacklist the access token[W.I.P](prevents possible misuse if the token is stolen), the access and refresh tokens are destroyed at the client side. If you use this trick, then don't forget to create an url '/api/token/logout/' in the backend. and follow the instructions here: [](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/blacklist_app.html)
